### ISSUE TITLE
EnsureOwnerReference should work with meta.OwnerReference

### ISSUE THREAD

**Issue by calind** [appscode/kutil#163]
Currently `EnsureOwnerReference` and `RemoveOwnerReference` take as arguments `core.ObjectReference`, but the `ObjectMeta.OwnerReferences` is an array of `meta.OwnerReference`.

I think that for the sake of consistentcy, the two functions should take as arguments `meta.OwnerRerence`.

What are your thoughts about this?

**Comment by tamalsaha** [comment]
Sorry, this got lost in the Github notifications. :(

I think this makes sense.

**Comment by tamalsaha** [comment]
Actually on second thought, I don't think it makes sense. We use  the EventRecorder which takes the ObjectReference. So, in code, you can get once reference and use that for both writing events against that object or make that an owner of some other resource.
