### ISSUE TITLE
Can't convert apps/v1 Deployment to apps/v1beta1 through internal version

### ISSUE THREAD

**Issue by emruz-hossain** [appscode/kutil#95]
### Details:
while converting like for apps group
```go
internalObj := &apps.StatefulSet{}
err := legacyscheme.Scheme.Convert(v1Obj, internalObj, nil)
if err != nil {
	log.Fatal(err)
}
v1beta1Obj := &v1beta1.StatefulSet{}
err = legacyscheme.Scheme.Convert(internalObj, v1beta1Obj, nil)
if err != nil {
	log.Fatal(err)
}
```
Here,
```go
internalObj := &apps.StatefulSet{}
```
is ok but can't write
```go
internalObj := &apps.Deployment{}
```
Reason: unversioned [types.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/types.go) of apps group has only StatefulSet

**Comment by tamalsaha** [comment]
apimachinery/pkg/runtime/serializer/versioning/versioning.go

**Comment by tamalsaha** [comment]
Fixed by conversion via internal type
